spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/sbb?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
    logback:
      rollingpolicy:
        max-history: 30
        max-file-size: 100MB
        file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
    file:
      name: logs/board.log
    pattern:
      dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul