spring:
  datasource:
    url: jdbc:mysql://20.196.218.174:3306/sbb?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbmasteruser
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

logging:
    logback:
      rollingpolicy:
        max-history: 30
        max-file-size: 100MB
        file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
    file:
      name: logs/board.log
    pattern:
      dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul