version: "3.6"

services:
  board:
    container_name: "board"
    image: "ghcr.io/sukkyun2/sbb"

    restart: always
    ports:
      - "${APP_PORT:-8081}:8080"
    volumes:
      - data-volume:/pinpoint-agent
    environment:
      JAVA_OPTS: "-javaagent:/pinpoint-agent/pinpoint-bootstrap-${PINPOINT_VERSION}.jar -Dpinpoint.agentId=${AGENT_ID} -Dpinpoint.applicationName=${APP_NAME} -Dpinpoint.profiler.profiles.active=${SPRING_PROFILES}"
    networks:
      - pinpoint
    depends_on:
      - pinpoint-agent

  pinpoint-agent:
    container_name: "${PINPOINT_AGENT_NAME}"
    image: "pinpointdocker/pinpoint-agent:${PINPOINT_VERSION}"

    restart: unless-stopped

    networks:
      - pinpoint
    volumes:
      - data-volume:/pinpoint-agent
    environment:
      - COLLECTOR_IP=${COLLECTOR_IP}
      - COLLECTOR_TCP_PORT=${COLLECTOR_TCP_PORT}
      - COLLECTOR_STAT_PORT=${COLLECTOR_STAT_PORT}
      - COLLECTOR_SPAN_PORT=${COLLECTOR_SPAN_PORT}
      - PROFILER_SAMPLING_TYPE=${PROFILER_SAMPLING_TYPE} 
      - PROFILER_SAMPLING_COUNTING_SAMPLING_RATE=${PROFILER_SAMPLING_COUNTING_SAMPLING_RATE}
      - PROFILER_SAMPLING_PERCENT_SAMPLING_RATE=${PROFILER_SAMPLING_PERCENT_SAMPLING_RATE}
      - PROFILER_SAMPLING_NEW_THROUGHPUT=${PROFILER_SAMPLING_NEW_THROUGHPUT}
      - PROFILER_SAMPLING_CONTINUE_THROUGHPUT=${PROFILER_SAMPLING_CONTINUE_THROUGHPUT}
      - DEBUG_LEVEL=${AGENT_DEBUG_LEVEL}

volumes:
  data-volume:

networks:
  pinpoint:
    driver: bridge
